### ISSUE TITLE
使用naiveui+ViteSSR报document is not defined错误

### ISSUE THREAD

**Issue by Ocyss** [07akioni/css-render#1103]
### TuSimple/naive-ui version (版本)
2.34.3

### Vue version (Vue 版本)
3.2.47

### Browser and its version (浏览器及其版本)
Chromium 102.0.5005.167

### System and its version (系统及其版本)
Win11 22H2

### Reappearance link (重现链接)
<https://github.com/Ocyss/QiuBlog/tree/ssr>

### Reappearance steps (重现步骤)
Using `n-popover` ,  `n-tabs` ,  `n-menu` all report errors
使用 `n-popover` ，`n-tabs` ，`n-menu` 都会报错

### Expected results (期望的结果)
正常使用
Normal use

### Actual results (实际的结果)
```
ReferenceError: document is not defined
    at queryElement (E:\Vue\QiuBlog\Blog\web\node_modules\css-render\lib\utils.js:17:5)
    at mount (E:\Vue\QiuBlog\Blog\web\node_modules\css-render\lib\mount.js:59:52)
    at Object.wrappedMount [as mount] (E:\Vue\QiuBlog\Blog\web\node_modules\css-render\lib\c.js:14:45)
    at setup (/node_modules/vueuc/es/binder/src/Follower.js:92:15)
    at callWithErrorHandling (E:\Vue\QiuBlog\Blog\web\node_modules\@vue\runtime-core\dist\runtime-core.cjs.js:171:22)
    at setupStatefulComponent (E:\Vue\QiuBlog\Blog\web\node_modules\@vue\runtime-core\dist\runtime-core.cjs.js:7194:29)
    at setupComponent (E:\Vue\QiuBlog\Blog\web\node_modules\@vue\runtime-core\dist\runtime-core.cjs.js:7149:11)
    at renderComponentVNode (E:\Vue\QiuBlog\Blog\web\node_modules\@vue\server-renderer\dist\server-renderer.cjs.js:628:17)
    at renderVNode (E:\Vue\QiuBlog\Blog\web\node_modules\@vue\server-renderer\dist\server-renderer.cjs.js:755:22)
    at renderComponentSubTree (E:\Vue\QiuBlog\Blog\web\node_modules\@vue\server-renderer\dist\server-renderer.cjs.js:719:13)
```

**Comment by Sunpacker** [comment]
how to solve?
