### ISSUE TITLE
SSR fails: document is not defined

### ISSUE THREAD

**Issue by jaulz** [07akioni/css-render#564]
While rendering the `Tabs` component from `naive-ui` in SSR mode, the process fails with this error:
````
[Vue warn]: Unhandled error during execution of setup function 
  at <XScroll ref="xScrollInstRef" onScroll=fn<debounced> >
ReferenceError: document is not defined
    at Object.queryElement (/dev/node_modules/css-render/lib/utils.js:17:5)
    at Object.mount (/dev/node_modules/css-render/lib/mount.js:62:35)
    at Object.wrappedMount [as mount] (/dev/node_modules/css-render/lib/c.js:14:35)
    at setup (/dev/node_modules/vueuc/lib/x-scroll/src/index.js:32:16)
    at callWithErrorHandling (/dev/node_modules/@vue/runtime-core/dist/runtime-core.cjs.js:6650:22)
````

**Comment by Talljack** [comment]
waht 's your ssrAdapter?
